# 2.Pythonの基本

## 2.1 四則演算

### 四則演算の利用

In [1]:
1+2

3

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

### 2.1.2 累乗

In [3]:
2**8

256

## 2.2 変数

### 変数を利用した計算

In [4]:
x = 1
y = 1/3
x + y

1.3333333333333333

### 変数名の表記

In [6]:
Data_1 = 1 / 5 
Data_2 = 3 / 5
Data_1 + Data_2

0.8

## 2.3 型

### 2.3.2 型の調査

In [7]:
type(100)

int

In [8]:
type(100.1)

float

In [10]:
x=100
type(x)

int

In [11]:
x=100.1
type(x)

float

### 2.3.3 文字列

In [12]:
x = 'learning'
type(x)

str

## 2.4 print文

### 2.4.1 print文の利用

In [13]:
x = 1/3
x
y = 2/3
y

0.6666666666666666

In [14]:
x = 1/3
print(x)
y = 2/3
print(y)

0.3333333333333333
0.6666666666666666


### 2.4.2 文字列と組み合わせた数値の表示1

In [15]:
print('x= ' + str(x))

x= 0.3333333333333333


### 2.4.3 文字列と組み合わせた数値の表示2

In [16]:
print('weight = {}kg'.format(x))

weight = 0.3333333333333333kg


In [17]:
x=1/3
y=1/7
z=1/4
print('weight : {0}kg, {1}kg, {2}kg'.format(x, y, z))

weight : 0.3333333333333333kg, 0.14285714285714285kg, 0.25kg


In [18]:
print('weight : {0:.2f}kg, {1:.2f}kg, {2:.2f}kg'.format(x, y, z))

weight : 0.33kg, 0.14kg, 0.25kg


## 2.5 list（リスト、配列変数）

### listの利用

In [19]:
x = [1, 1, 2, 3, 5] # listの定義
print(x)

[1, 1, 2, 3, 5]


In [20]:
x[0]

1

In [21]:
x[2]

2

In [22]:
print(type(x))

<class 'list'>


In [23]:
print(type(x[0]))

<class 'int'>


In [25]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [26]:
x = [1, 1, 2, 3, 5] 
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [27]:
x = [1, 1, 2, 3, 5] 
len(x)

5

### 2.5.2 2次元の配列

In [28]:
a = [[1,2,3], [4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [29]:
a = [[1,2,3], [4,5,6]]
print(a[0][1])

2


### 2.5.3 連続した整数の配列の作成

In [31]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


In [32]:
print(y)

range(5, 10)


In [34]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


In [35]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 2.6 tuple（タプル）

### 2.6.1 tupleの利用

In [37]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


In [38]:
a[1]

2

### 長さが1のtuple

In [39]:
a = (1)
type(a)

int

In [40]:
a = (1,)
type(a)

tuple

## 2.7 if文

### 2.7.1 if文の利用

In [43]:
x = 11
if x >10:
    print('x is ')
    print(' larager than 10.')
else:
    print('x is smaller than 11')

x is 
 larager than 10.


In [44]:
x>10

True

In [45]:
type(x>10)

bool

### 2.7.2 比較演算子

In [47]:
x = 15
if 10 < x and x < 20:
    print('x is between 10 and 20')

x is between 10 and 20


## 2.8 for文

### 2.8.1 for文の利用 

In [48]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [50]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)): # len(num)はnumの要素数
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


### 2.8.2 enumerateの利用

In [51]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num): # numのindexとnum[index]の値が、i と n に入る
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


## 2.9 ベクトル

In [52]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

### 2.9.1 Numpyの利用

In [53]:
import numpy as np

### 2.9.2 ベクトルの定義

In [54]:
x = np.array([1, 2])
x

array([1, 2])

In [55]:
print(x)

[1 2]


In [57]:
x = np.array([1, 2])
y = np.array([3, 4])
print(x + y)

[4 6]


In [58]:
type(x)

numpy.ndarray

### 2.9.3 要素の参照

In [59]:
x = np.array([1, 2])
print(x[0])

1


### 2.9.4 要素の書き換え

In [60]:
x = np.array([1, 2])
x[0] = 100
print(x)

[100   2]


### 2.9.5 連続した整数のベクトルの作成

In [62]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [63]:
print(np.arange(5, 10))

[5 6 7 8 9]


### 2.9.6 ndarray型の注意点

In [67]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b =' + str(a))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[100   1]


In [68]:
a = np.array([1, 1])
b = a.copy()
print('a =' + str(a))
print('b =' + str(a))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[1 1]


## 2.10 行列

### 2.10.1 行列の定義

In [69]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


### 2.10.2 行列のサイズ

In [70]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [71]:
h, w = x.shape
print(h)
print(w)

2
3


### 2.10.3 要素の参照

In [73]:
x = np.array([[1, 2,  3], [4, 5, 6]])
print(x[1][2])

6


### 2.10.4 要素の書き換え

In [75]:
x = np.array([[1, 2,  3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


### 2.10.5 要素が0や1のndarrayの作成

In [76]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [78]:
x = np.zeros((2, 10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [79]:
x = np.ones((2, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 2.10.6 要素がランダムな行列の作成

In [81]:
np.random.rand(2, 3)

array([[0.105844  , 0.47047299, 0.75319984],
       [0.35411414, 0.24787295, 0.99035986]])

### 2.10.7 行列のサイズの変更

In [82]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [84]:
a = a.reshape(2, 5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]
