# 2.Pythonの基本

## 2.1 四則演算

### 四則演算の利用

In [1]:
1+2

3

In [2]:
(1 + 2 * 3 - 4) / 5

0.6

### 2.1.2 累乗

In [3]:
2**8

256

## 2.2 変数

### 変数を利用した計算

In [4]:
x = 1
y = 1/3
x + y

1.3333333333333333

### 変数名の表記

In [5]:
Data_1 = 1 / 5 
Data_2 = 3 / 5
Data_1 + Data_2

0.8

## 2.3 型

### 2.3.2 型の調査

In [6]:
type(100)

int

In [7]:
type(100.1)

float

In [8]:
x=100
type(x)

int

In [9]:
x=100.1
type(x)

float

### 2.3.3 文字列

In [10]:
x = 'learning'
type(x)

str

## 2.4 print文

### 2.4.1 print文の利用

In [11]:
x = 1/3
x
y = 2/3
y

0.6666666666666666

In [12]:
x = 1/3
print(x)
y = 2/3
print(y)

0.3333333333333333
0.6666666666666666


### 2.4.2 文字列と組み合わせた数値の表示1

In [13]:
print('x= ' + str(x))

x= 0.3333333333333333


### 2.4.3 文字列と組み合わせた数値の表示2

In [14]:
print('weight = {}kg'.format(x))

weight = 0.3333333333333333kg


In [15]:
x=1/3
y=1/7
z=1/4
print('weight : {0}kg, {1}kg, {2}kg'.format(x, y, z))

weight : 0.3333333333333333kg, 0.14285714285714285kg, 0.25kg


In [16]:
print('weight : {0:.2f}kg, {1:.2f}kg, {2:.2f}kg'.format(x, y, z))

weight : 0.33kg, 0.14kg, 0.25kg


## 2.5 list（リスト、配列変数）

### listの利用

In [17]:
x = [1, 1, 2, 3, 5] # listの定義
print(x)

[1, 1, 2, 3, 5]


In [18]:
x[0]

1

In [19]:
x[2]

2

In [20]:
print(type(x))

<class 'list'>


In [21]:
print(type(x[0]))

<class 'int'>


In [22]:
s = ['SUN', 1, 'MON', 2]
print(type(s[0]))
print(type(s[1]))

<class 'str'>
<class 'int'>


In [23]:
x = [1, 1, 2, 3, 5] 
x[3] = 100
print(x)

[1, 1, 2, 100, 5]


In [24]:
x = [1, 1, 2, 3, 5] 
len(x)

5

### 2.5.2 2次元の配列

In [25]:
a = [[1,2,3], [4,5,6]]
print(a)

[[1, 2, 3], [4, 5, 6]]


In [26]:
a = [[1,2,3], [4,5,6]]
print(a[0][1])

2


### 2.5.3 連続した整数の配列の作成

In [27]:
y = range(5, 10)
print(y[0], y[1], y[2], y[3], y[4])

5 6 7 8 9


In [28]:
print(y)

range(5, 10)


In [29]:
z = list(range(5, 10))
print(z)

[5, 6, 7, 8, 9]


In [30]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

## 2.6 tuple（タプル）

### 2.6.1 tupleの利用

In [31]:
a = (1, 2, 3)
print(a)

(1, 2, 3)


In [32]:
a[1]

2

### 長さが1のtuple

In [33]:
a = (1)
type(a)

int

In [34]:
a = (1,)
type(a)

tuple

## 2.7 if文

### 2.7.1 if文の利用

In [35]:
x = 11
if x >10:
    print('x is ')
    print(' larager than 10.')
else:
    print('x is smaller than 11')

x is 
 larager than 10.


In [36]:
x>10

True

In [37]:
type(x>10)

bool

### 2.7.2 比較演算子

In [38]:
x = 15
if 10 < x and x < 20:
    print('x is between 10 and 20')

x is between 10 and 20


## 2.8 for文

### 2.8.1 for文の利用 

In [39]:
for i in [1, 2, 3]:
    print(i)

1
2
3


In [40]:
num = [2, 4, 6, 8, 10]
for i in range(len(num)): # len(num)はnumの要素数
    num[i] = num[i] * 2
print(num)

[4, 8, 12, 16, 20]


### 2.8.2 enumerateの利用

In [41]:
num = [2, 4, 6, 8, 10]
for i, n in enumerate(num): # numのindexとnum[index]の値が、i と n に入る
    num[i] = n * 2
print(num)

[4, 8, 12, 16, 20]


## 2.9 ベクトル

In [42]:
[1, 2] + [3, 4]

[1, 2, 3, 4]

### 2.9.1 Numpyの利用

In [43]:
import numpy as np

### 2.9.2 ベクトルの定義

In [44]:
x = np.array([1, 2])
x

array([1, 2])

In [45]:
print(x)

[1 2]


In [46]:
x = np.array([1, 2])
y = np.array([3, 4])
print(x + y)

[4 6]


In [47]:
type(x)

numpy.ndarray

### 2.9.3 要素の参照

In [48]:
x = np.array([1, 2])
print(x[0])

1


### 2.9.4 要素の書き換え

In [49]:
x = np.array([1, 2])
x[0] = 100
print(x)

[100   2]


### 2.9.5 連続した整数のベクトルの作成

In [50]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [51]:
print(np.arange(5, 10))

[5 6 7 8 9]


### 2.9.6 ndarray型の注意点

In [52]:
a = np.array([1, 1])
b = a
print('a =' + str(a))
print('b =' + str(a))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[100   1]


In [53]:
a = np.array([1, 1])
b = a.copy()
print('a =' + str(a))
print('b =' + str(a))
b[0] = 100
print('b =' + str(b))
print('a =' + str(a))

a =[1 1]
b =[1 1]
b =[100   1]
a =[1 1]


## 2.10 行列

### 2.10.1 行列の定義

In [54]:
x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)

[[1 2 3]
 [4 5 6]]


### 2.10.2 行列のサイズ

In [55]:
x = np.array([[1, 2, 3], [4, 5, 6]])
x.shape

(2, 3)

In [56]:
h, w = x.shape
print(h)
print(w)

2
3


### 2.10.3 要素の参照

In [57]:
x = np.array([[1, 2,  3], [4, 5, 6]])
print(x[1][2])

6


### 2.10.4 要素の書き換え

In [58]:
x = np.array([[1, 2,  3], [4, 5, 6]])
x[1, 2] = 100
print(x)

[[  1   2   3]
 [  4   5 100]]


### 2.10.5 要素が0や1のndarrayの作成

In [59]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [60]:
x = np.zeros((2, 10))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [61]:
x = np.ones((2, 10))
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 2.10.6 要素がランダムな行列の作成

In [62]:
np.random.rand(2, 3)

array([[0.04054216, 0.54322769, 0.51945971],
       [0.11397466, 0.44686357, 0.56456983]])

### 2.10.7 行列のサイズの変更

In [63]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [64]:
a = a.reshape(2, 5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 行列（ndarray）の四則演算

### 行列における四則演算

In [65]:
x = np.array([[4, 4, 4], [8, 8, 8]])
y = np.array([[1, 1, 1], [2, 2, 2]])
print(x + y)

[[ 5  5  5]
 [10 10 10]]


### 2.11.2 スカラー X 行列

In [67]:
x = np.array([[4, 4, 4], [8, 8, 8]])
print(10 * x)

[[40 40 40]
 [80 80 80]]


### 2.11.3 算術関数

In [69]:
x = np.array([[4,4,4],[9,9,9]])
print(np.sqrt(x)) # 平方根

[[2. 2. 2.]
 [3. 3. 3.]]


### 2.11.4 行列積の計算

In [70]:
v = np.array([[1, 2, 3], [4,5,6]])
w = np.array([[1,1], [2,2], [3,3]])
print(v.dot(w))

[[14 14]
 [32 32]]


## 2.12 スライシング

### 2.12.1 スライシングの利用 

In [72]:
x = np.arange(10)
print(x)
print(x[:5])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]


In [73]:
print(x[5:])

[5 6 7 8 9]


In [74]:
print(x[3:8])

[3 4 5 6 7]


In [75]:
print(x[3:8:2])

[3 5 7]


In [76]:
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


In [77]:
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
print(y[:2])

[[1 2 3]
 [4 5 6]]


In [79]:
print(y[:2, 1:2])

[[2]
 [5]]


## 2.13 条件を満たすデータの書き換え

### 2.13.1 bool配列の利用

In [80]:
x = np.array([1, 1, 2, 3, 5, 8, 13])
x > 3

array([False, False, False, False,  True,  True,  True])

In [81]:
x[x > 3]

array([ 5,  8, 13])

In [83]:
x[x > 3] = 999
print(x)

[  1   1   2   3 999 999 999]


## 2.14 Help

### Helpの利用

In [85]:
import numpy as np
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype='l')
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; see `random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distribution (see above fo

## 2.15 関数

### 2.15.1 関数の利用

In [87]:
def my_func1():
    print('Hi!')
# 関数my_func1()の定義はここまで

my_func1() # 関数を実行

Hi!


In [88]:
def my_func2(a, b):
    c = a + b
    return c

my_func2(1, 2)

3

### 2.15.2 引数と戻り値 

In [89]:
def my_func3(D):
    m = np.mean(D)
    s = np.std(D)
    return m, s

In [90]:
data = np.random.randn(100)
data_mean, data_std = my_func3(data)
print('mean:{0:.2f}, std:{1:.2f}'.format(data_mean, data_std))

mean:0.02, std:1.03


In [91]:
print(data_mean)

0.015257291065114751


In [92]:
print(data_std)

1.0289899436815715


In [95]:
output = my_func3(data)
# print(data)
print(output)
print(type(output))
print('mean:{0:.2f}, std:{1:.2f}'.format(output[0], output[1]))

(0.015257291065114751, 1.0289899436815715)
<class 'tuple'>
mean:0.02, std:1.03


## 2.16 ファイル保存

### 2.16.1 1つのndarray型の保存

In [98]:
data = np.array([1, 1, 2, 3, 5, 8, 13])
print(data)

np.save('datafile.npy', data) # ファイル保存
data = [] # データ消去
print(data)

data = np.load('datafile.npy') # ファイル読み出し
print(data)

[ 1  1  2  3  5  8 13]
[]
[ 1  1  2  3  5  8 13]


### 2.16.2 複数のndarray型の保存

In [99]:
data1 = np.array([1, 2, 3])
data2 = np.array([10, 20, 30])
np.savez('datafile2.npz', data1=data1, data2=data2) # ファイル保存
data1 = [] # データ消去
data2 = []
outfile = np.load('datafile2.npz') # ファイル読み出し
print(outfile.files) # 格納している全データの表示
data1 = outfile['data1']
data2 = outfile['data2']
print(data1)
print(data2)

['data1', 'data2']
[1 2 3]
[10 20 30]
